language: python
python: 3.5
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
  # set up channels with bioconda
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  
  # create conda environment
  - conda create -q -n test-environment python=3.5 pandas ete3 goatools wget numpy statsmodels r-ggplot2 biopython
  - source activate test-environment
  
  # build package
  - python setup.py install

script:
  pwd && python -m unittest discover tests

notifications:
  email: false
