name: metaquantome
channels:
- defaults
- bioconda
- conda-forge
- r
dependencies:
- python==3.5.*
- ete3==3.1.1
- goatools==0.7.11
- statsmodels==0.8.0
- biopython==1.70
- pandas==0.23.*
- r-gplots==3.0.1
- r-ggplot2
- r-base==3.4.*
- r-jsonlite=1.5
- libiconv
