name: metaquantome
channels:
- defaults
- bioconda
- conda-forge
- r
dependencies:
- python>=3
- ete3==3.1.*
- goatools==0.7.*
- statsmodels==0.8.*
- biopython==1.73.*
- pandas==0.23.*
- numpy 1.15.*
- r-gplots==3.0.*
- r-ggplot2==3.0.*
- r-base==3.5.1
- r-scico=1.1.0
- r-dplyr=0.8.0.1
- r-tidyr=0.8.3
- r-jsonlite=1.5.*
- libiconv 1.15.*
